### ISSUE TITLE
data:application/pdf;base64,base64... 电子签章展示问题，请大佬赶紧提供显示和隐藏电子签章的参数入口，不然我就叫二营长把意大利......

### ISSUE THREAD

**Issue by jimsonbuilder** [FranckFreiburger/vue-pdf#252]
<pdf
        v-for="i in numPages"
        :key="i"
        ref="myPdfComponent"
        :src="src"
        :page="i"
      />

// 请提供显示和隐藏电子签章的口子，通知我：870255589@qq.com
// Please provide an API entry for displaying and hiding electronic signatures,and call me:870255589@qq.com,thanks a lot.

**Comment by BiscuitPanda** [comment]
Is this problem solved now?

**Comment by cuocuo-46** [comment]
> Is this problem solved now?

I have the same problem.And the problem is not resolved now.

**Comment by ruuuup** [comment]
Is this problem solved now?

**Comment by jimsonbuilder** [comment]
The problem is still not solved......QAQ，but i have another way to solve it,as below.

`<iframe
        :src="'static/pdf/web/viewer.html?file=' + this.contactUrl + '&.pdf'"
        class="em-cls"
      />`

`
    getPdfBase64() {
      const data = new FormData()
      data.append('filePath', this.agreementFileUrl)
      getPdfBase64(data)
        .then((data) => {
          Toast.clear()
          this.pdfBase64Str = 'data:application/pdf;base64,' + data.data

          // base64转blob对象
          function ataURItoBlob(base64Data) {
            let byteString
            if (base64Data.split(',')[0].indexOf('base64') >= 0) { byteString = atob(base64Data.split(',')[1]) }
            // base64 解码
            else {
              byteString = unescape(base64Data.split(',')[1])
            }
            const mimeString = base64Data
              .split(',')[0]
              .split(':')[1]
              .split(';')[0] // mime类型 -- image/png
            const ia = new Uint8Array(byteString.length) // 创建视图
            for (let i = 0; i < byteString.length; i++) {
              ia[i] = byteString.charCodeAt(i)
            }
            const blob = new Blob([ia], {
              type: mimeString
            })
            return blob
          }

          const contractauthBlob = ataURItoBlob(this.pdfBase64Str)

          this.contactUrl = window.URL.createObjectURL(
            new Blob([contractauthBlob])
          )
        })
    }
`
